# Paso 1: Crear un recurso de Azure Static Web Apps en Azure Portal
#   - Ir a Azure Portal y crear un recurso de tipo "Static Web Apps"
#   - Seleccionar "Free" como plan de tarifa
#   - Completar la informaci n de configuraci n b sica
#   - Crear el recurso

# Paso 2: Crear una variable de entorno en Azure Static Web Apps
#   - Ir a la p gina de configuraci n del recurso de Azure Static Web Apps
#   - Hacer clic en "Configuraci n" en la barra de navegaci n lateral
#   - Hacer clic en "Variables de entorno"
#   - Crear una variable de entorno con nombre "GITHUB_TOKEN" y valor el token de acceso personal de GitHub

# Paso 3: Configurar el pipeline de Azure Static Web Apps
#   - En el archivo azure.yaml, reemplazar "ACTION_NAME" con el nombre de la acci n que se va a crear
#   - En el archivo azure.yaml, reemplazar "https://api.example.com" con la URL de la API de la aplicaci n
#   - En el archivo azure.yaml, reemplazar "secrets.GITHUB_TOKEN" con la variable de entorno "GITHUB_TOKEN" creada en el paso 2

# Paso 4: Habilitar la conexi n entre GitHub y Azure Static Web Apps
#   - Ir a la p gina de configuraci n del recurso de Azure Static Web Apps
#   - Hacer clic en "Configuraci n" en la barra de navegaci n lateral
#   - Hacer clic en "Or genes"
#   - Hacer clic en "GitHub"
#   - Autorizar la conexi n entre GitHub y Azure Static Web Apps

name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install

      - name: Build and deploy
        env:
          AZURE_STATIC_WEB_APPS_ACTION: "ACTION_NAME"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REACT_APP_API_URL: "https://api.example.com"
        run: |
          npm run build
          npx azure-static-web-apps-cli deploy --action "$AZURE_STATIC_WEB_APPS_ACTION" --output-location "build" --token "$GITHUB_TOKEN"
